export const actionsEnums = {
  MEMBER_REQUEST: "MEMBER_REQUEST",
  MEMBER_REQUEST_COMPLETED: "MEMBER_REQUEST_COMPLETED",
  MEMBER_REQUEST_INIT: "MEMBER_REQUEST_INIT",
  MEMBER_REQUEST_ERROR: "MEMBER_REQUEST_ERROR",
  MEMBER_REQUEST_FINALLY: "MEMBER_REQUEST_FINALLY",
  MEMBER_REQUEST_SCROLL: "MEMBER_REQUEST_SCROLL"

};
